#**Deep Neural Network Implementation on IRIS Data**

###**Import the necessary packages**

In [5]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

###**Load the IRIS Dataset**

In [6]:
# Dataset
iris_data = load_iris()
X = iris_data.data
y = iris_data.target
y = y.reshape(-1, 1)

In [7]:
# Check the dimensions
print(X.shape)
print(y.shape)

(150, 4)
(150, 1)


###**OneHotEncoder**

The output has 3 classes, so the labels will have 3 values
1. First Class: (1, 0, 0)
2. Second Class: (0, 1, 0)
3. Third Class: (0, 0, 1)

In [8]:
encoder = OneHotEncoder()
y = encoder.fit_transform(y).toarray()

In [9]:
# Check the labels
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

###**Split the data into Test and Training Data**

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

###**Create the Model**

In [11]:
model = Sequential()

# Now add layers to the Sequential model
# We add 6 Hidden layers with "ReLU" activation function

# First hidden layer works as the input layer
model.add(Dense(16, input_dim = 4, activation = 'relu')) # Input Layer

model.add(Dense(16, input_dim = 16, activation = 'relu')) # Hidden Layer 1
model.add(Dense(16, input_dim = 16, activation = 'relu')) # Hidden Layer 2
model.add(Dense(16, input_dim = 16, activation = 'relu')) # Hidden Layer 3
model.add(Dense(16, input_dim = 16, activation = 'relu')) # Hidden Layer 4
model.add(Dense(16, input_dim = 16, activation = 'relu')) # Hidden Layer 5
model.add(Dense(16, input_dim = 16, activation = 'relu')) # Hidden Layer 6

# Now add output layer with 1 output value and "Sigmoid" as activation function
model.add(Dense(3, input_dim = 16, activation = 'sigmoid')) # Output Layer

###**Compile the Model**

We can define the loss function as MSE or Negative Log Likelihood and Optimizer will find the right adjustments for the weights: SGD, Adagrad, ADAM...

In [12]:
model.compile(loss = 'categorical_crossentropy',
              optimizer = Adam(lr = 0.005),
              metrics = ['accuracy'])

###**Train the Model**

In [13]:
model.fit(X_train, 
          y_train, 
          epochs = 10000, 
          batch_size = 20, 
          verbose = 2)

Streaming output truncated to the last 5000 lines.
Epoch 7501/10000
6/6 - 0s - loss: 0.0446 - accuracy: 0.9833
Epoch 7502/10000
6/6 - 0s - loss: 0.0465 - accuracy: 0.9750
Epoch 7503/10000
6/6 - 0s - loss: 0.0434 - accuracy: 0.9750
Epoch 7504/10000
6/6 - 0s - loss: 0.0449 - accuracy: 0.9750
Epoch 7505/10000
6/6 - 0s - loss: 0.0442 - accuracy: 0.9750
Epoch 7506/10000
6/6 - 0s - loss: 0.0445 - accuracy: 0.9750
Epoch 7507/10000
6/6 - 0s - loss: 0.0486 - accuracy: 0.9750
Epoch 7508/10000
6/6 - 0s - loss: 0.0534 - accuracy: 0.9750
Epoch 7509/10000
6/6 - 0s - loss: 0.0449 - accuracy: 0.9750
Epoch 7510/10000
6/6 - 0s - loss: 0.0508 - accuracy: 0.9750
Epoch 7511/10000
6/6 - 0s - loss: 0.0492 - accuracy: 0.9750
Epoch 7512/10000
6/6 - 0s - loss: 0.0430 - accuracy: 0.9833
Epoch 7513/10000
6/6 - 0s - loss: 0.0630 - accuracy: 0.9750
Epoch 7514/10000
6/6 - 0s - loss: 0.0483 - accuracy: 0.9750
Epoch 7515/10000
6/6 - 0s - loss: 0.0486 - accuracy: 0.9750
Epoch 7516/10000
6/6 - 0s - loss: 0.0468 - accura

###**Evaluating the Model**

In [14]:
results = model.evaluate(X_test, y_test, use_multiprocessing = True)
print("Training is finished. The loss and accuracy values are: ")
print(results)

1/1 [==============================] - 0s 216ms/step - loss: 0.0300 - accuracy: 1.0000
Training is finished. The loss and accuracy values are: 
[0.030046997591853142, 1.0]


###**Making Predictions**

In [15]:
def predict_class(new):
  predict = model.predict(new.reshape(-1,4))
  cls = np.argmax(predict)
  classes = ['Setosa', 'Versicolor', 'Virginica']
  return classes[cls]

input_array = X[11]
predicted = predict_class(input_array)
print(f"Input array is: {input_array}")
print(f"The predicted class is: {predicted}")

Input array is: [4.8 3.4 1.6 0.2]
The predicted class is: Setosa
